version: '2'
services:
  db:
    restart: always
    image: postgres:9.6.0
    expose:
      - "5432"
    volumes:
      - "{{ project_name }}_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  
  rabbit:
    restart: always
    image: rabbitmq:3.6.12
    expose:
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_user_default_pass
    ports:
      - "5672:5672"
      - "15672:15672"


  {{ project_name }}:
    restart: always
    image: oratio/kale:1.0.0
    depends_on:
      - redis
      - rabbit
    environment:
      DJANGOENV: development
      ENVIRONMENT: development
      PYTHON: python
      PROJECT_NAME: {{ project_name }}
      TERM: xterm
      ROLE: development
    links:
      - db:postgres
      - redis
      - rabbit
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    expose:
      - "80"
      - "443"
      - "8000"
    volumes:
      - .:/var/www
      - ~/.aws/config:/root/.aws/config
    working_dir: /var/www
    command: bash -lc "pip install invoke jinja2 && invoke -r roles $${ROLE}"

volumes:
  {{ project_name }}_db_data:
    external: true
